version: '3.9'  

services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: ${DOCMOST_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  docmost:
    image: docmost/docmost:0.6
    container_name: docmost
    depends_on:
      - db
      - redis
    restart: unless-stopped
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'auV5TfdY3yF69RJM56wPT' 
      DATABASE_URL: 'postgresql://docmost:${DOCMOST_DB_PASSWORD}@db:5432/docmost?schema=public' 
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    volumes:
      - docmost:/app/data/storage
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - app-network
  
volumes:
  docmost:
  db_data:
  redis_data:

networks:
  app-network:
    driver: bridge
